CREATE TABLE IF NOT EXISTS t_p90536134_security_requirement.requirements (
    id                      TEXT PRIMARY KEY,
    name                    TEXT NOT NULL,
    technology_id           TEXT,
    tech_domain_id          TEXT,
    description             TEXT NOT NULL DEFAULT '',
    req_type                TEXT NOT NULL DEFAULT 'Техническое',
    criticality             TEXT NOT NULL DEFAULT 'Средний',
    control_metric          TEXT NOT NULL DEFAULT '',
    control_description     TEXT NOT NULL DEFAULT '',
    tags                    TEXT[] NOT NULL DEFAULT '{}',
    version                 TEXT NOT NULL DEFAULT '1.0.0',
    status                  TEXT NOT NULL DEFAULT 'В разработке',
    norm_doc_link           TEXT NOT NULL DEFAULT '',
    environments            TEXT[] NOT NULL DEFAULT '{}',
    stages                  TEXT[] NOT NULL DEFAULT '{}',
    procurement             TEXT NOT NULL DEFAULT '',
    ext_with_iod            TEXT NOT NULL DEFAULT 'Не требуется',
    ext_without_iod         TEXT NOT NULL DEFAULT 'Не требуется',
    int_with_iod            TEXT NOT NULL DEFAULT 'Не требуется',
    int_without_iod         TEXT NOT NULL DEFAULT 'Не требуется',
    score_value             INTEGER NOT NULL DEFAULT 1,
    score_weight            INTEGER NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
